- name: Install yum-utils
  ansible.builtin.dnf:
    name: yum-utils
    state: present

- name: Add Docker repo
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'

- name: Install Docker
  ansible.builtin.dnf:
    name: "{{ docker_engine_docker_packages }}"
    state: present
    update_cache: true
  loop: "{{ docker_engine_docker_packages }}"

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add ec2-user to docker group
  ansible.builtin.user:
    name: ec2-user
    groups: docker
    append: true

